export const mockQuestions = [
  {
    _id: '1',
    text: 'Explain the concept of Virtual Memory and its implementation using Paging.',
    subject: 'Operating Systems',
    chapter: 'Memory Management',
    difficulty: 'medium',
    marks: 10,
    year: 3,
    semester: 1,
    branch: 'CSE',
    examYear: 2023,
    examSession: 'End Sem',
    questionType: 'theory',
    frequency: 5,
    isImportant: true,
    isPYQ: true,
    solution: 'Virtual memory is a memory management capability of an operating system (OS) that uses hardware and software to allow a computer to compensate for physical memory shortages by temporarily transferring data from random access memory (RAM) to disk storage.',
    tags: ['OS', 'Memory', 'Paging'],
    topic: 'Paging'
  },
  {
    _id: '2',
    text: 'Solve the following recurrence relation: T(n) = 2T(n/2) + n',
    subject: 'Design and Analysis of Algorithms',
    chapter: 'Divide and Conquer',
    difficulty: 'hard',
    marks: 5,
    year: 3,
    semester: 1,
    branch: 'CSE',
    examYear: 2022,
    examSession: 'Mid Sem',
    questionType: 'numerical',
    frequency: 3,
    isImportant: true,
    isPYQ: true,
    solution: 'Using Master Theorem: a=2, b=2, f(n)=n. n^(log_b a) = n^(log_2 2) = n^1 = n. Since f(n) = Theta(n), Case 2 applies. T(n) = Theta(n log n).',
    tags: ['Algorithms', 'Recurrence', 'Master Theorem'],
    topic: 'Master Theorem'
  },
  {
    _id: '3',
    text: 'What is the difference between TCP and UDP? Explain with header formats.',
    subject: 'Computer Networks',
    chapter: 'Transport Layer',
    difficulty: 'medium',
    marks: 10,
    year: 3,
    semester: 2,
    branch: 'CSE',
    examYear: 2023,
    examSession: 'End Sem',
    questionType: 'theory',
    frequency: 8,
    isImportant: true,
    isPYQ: true,
    solution: 'TCP is connection-oriented, reliable, and slower. UDP is connectionless, unreliable, and faster. TCP header is 20-60 bytes, UDP header is 8 bytes.',
    tags: ['CN', 'TCP', 'UDP'],
    topic: 'Transport Protocols'
  },
  {
    _id: '4',
    text: 'Define Normalization. Explain 1NF, 2NF, and 3NF with examples.',
    subject: 'Database Management Systems',
    chapter: 'Relational Database Design',
    difficulty: 'easy',
    marks: 10,
    year: 2,
    semester: 2,
    branch: 'CSE',
    examYear: 2021,
    examSession: 'End Sem',
    questionType: 'theory',
    frequency: 10,
    isImportant: true,
    isPYQ: true,
    solution: 'Normalization is the process of organizing data in a database. 1NF: Atomic values. 2NF: No partial dependency. 3NF: No transitive dependency.',
    tags: ['DBMS', 'Normalization', 'SQL'],
    topic: 'Normalization'
  },
  {
    _id: '5',
    text: 'A process has 3 frames. The reference string is 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1. Calculate page faults using LRU.',
    subject: 'Operating Systems',
    chapter: 'Memory Management',
    difficulty: 'hard',
    marks: 10,
    year: 3,
    semester: 1,
    branch: 'CSE',
    examYear: 2022,
    examSession: 'Re Exam',
    questionType: 'numerical',
    frequency: 4,
    isImportant: false,
    isPYQ: true,
    solution: 'LRU replaces the least recently used page. Calculation steps...',
    tags: ['OS', 'LRU', 'Page Replacement'],
    topic: 'Page Replacement Algorithms'
  },
  {
    _id: '6',
    text: 'Explain the architecture of 8086 Microprocessor with a neat diagram.',
    subject: 'Microprocessors',
    chapter: '8086 Architecture',
    difficulty: 'medium',
    marks: 10,
    year: 2,
    semester: 2,
    branch: 'ECE',
    examYear: 2020,
    examSession: 'End Sem',
    questionType: 'theory',
    frequency: 6,
    isImportant: true,
    isPYQ: true,
    solution: '8086 is a 16-bit microprocessor. It has two units: BIU (Bus Interface Unit) and EU (Execution Unit).',
    tags: ['Microprocessor', '8086', 'Architecture'],
    topic: 'Microprocessor Architecture'
  },
  {
    _id: '7',
    text: 'Derive the expression for the efficiency of a Transformer.',
    subject: 'Electrical Machines',
    chapter: 'Transformers',
    difficulty: 'medium',
    marks: 5,
    year: 2,
    semester: 1,
    branch: 'EE',
    examYear: 2021,
    examSession: 'Mid Sem',
    questionType: 'theory',
    frequency: 5,
    isImportant: false,
    isPYQ: true,
    solution: 'Efficiency = Output Power / Input Power. Input Power = Output Power + Losses (Core + Copper).',
    tags: ['Electrical', 'Transformer', 'Efficiency'],
    topic: 'Transformer Efficiency'
  },
  {
    _id: '8',
    text: 'Explain the working of a 4-stroke petrol engine.',
    subject: 'Thermodynamics',
    chapter: 'IC Engines',
    difficulty: 'easy',
    marks: 5,
    year: 2,
    semester: 1,
    branch: 'ME',
    examYear: 2019,
    examSession: 'End Sem',
    questionType: 'theory',
    frequency: 7,
    isImportant: true,
    isPYQ: true,
    solution: 'Intake, Compression, Power, Exhaust strokes.',
    tags: ['Mechanical', 'IC Engine', 'Thermodynamics'],
    topic: 'IC Engines'
  }
];

export const mockSubjects = [
  'Operating Systems',
  'Design and Analysis of Algorithms',
  'Computer Networks',
  'Database Management Systems',
  'Microprocessors',
  'Electrical Machines',
  'Thermodynamics'
];

export const mockChapters = [
  'Memory Management',
  'Divide and Conquer',
  'Transport Layer',
  'Relational Database Design',
  '8086 Architecture',
  'Transformers',
  'IC Engines'
];
